resources:
- deployment.yaml
- service.yaml
replacements:
- source:
    kind: ConfigMap
    name: pipeline-vars
  targets:
  - select:
      kind: Deployment
      name: nginx
    fieldPaths:
    - spec.replicas
  - select:
      kind: Deployment
      name: nginx
    fieldPaths:
    - spec.template.spec.containers.[name=nginx].image
