# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: nginx
#   ports:
#   - port: 80
#     targetPort: 80
apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}
spec:
  type: {{SERVICE_TYPE}}
  selector:
    app: {{APP_NAME}}
  ports:
  - port: {{SERVICE_PORT}}
    targetPort: 80
