resources:
- ../../base

nameSuffix: -dev

commonLabels:
  env: dev

configMapGenerator:
- name: pipeline-vars
  literals:
  - REPLICAS=2
  - IMAGE=nginx:1.25
  - CPU_REQUEST=100m
  - MEMORY_REQUEST=128Mi
  - CPU_LIMIT=200m
  - MEMORY_LIMIT=256Mi
  - SERVICE_TYPE=LoadBalancer
  - SERVICE_PORT=80


# replicas:
# - name: nginx
#   count: 2
